### ISSUE TITLE
Problem with the examples

### ISSUE THREAD

**Issue by npearson72** [facebook/draft-js#101]
These instructions don't work for me:

```
git clone https://github.com/facebook/draft-js.git
cd draft-js
npm install
npm run build
```

I get this when running `npm run build`:

```
> draft-js@0.1.0 prebuild /Users/nathan/draft-js
> node node_modules/fbjs-scripts/node/check-dev-engines.js package.json


assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: Current node version is not supported for development, expected "5.1.0" to satisfy "4.x".
    at Object.<anonymous> (/Users/nathan/draft-js/node_modules/fbjs-scripts/node/check-dev-engines.js:39:3)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.1.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.1.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! draft-js@0.1.0 prebuild: `node node_modules/fbjs-scripts/node/check-dev-engines.js package.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the draft-js@0.1.0 prebuild script 'node node_modules/fbjs-scripts/node/check-dev-engines.js package.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the draft-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs draft-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls draft-js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nathan/draft-js/npm-debug.log
```

[npm-debug.log.zip](https://github.com/facebook/draft-js/files/148706/npm-debug.log.zip)

**Comment by spicyj** [comment]
#37 will fix this.

**Comment by npearson72** [comment]
Wow, that was fast. Thanks!
