### ISSUE TITLE
Editor breaks regularly on multiple block-deletion :: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by Robert-Fairley** [facebook/draft-js#1089]
I'm running into a bug and I can't seem to find a sound solution for it. I'm presently working on some sort of workaround as the project I'm working on is a little pressing. But this is a relatively large stumbling block as it's being designed for non-technical users.

**What is the current behavior?**
The editor will break, unpredictably, when handling deletions of multiple blocks at once. Again, unpredictably. I can't seem to reproduce the problem reliably, but can usually cause it to occur when I make an effort to do so.

To be more specific about the case, the users will be pasting large amounts of text from inDesign (with formatting) into the editor. I set the editor to strip formatting, but it retains all hard breaks -- which is a bit of a pain, but I've created another solution for that as well.

However when you couple a number of incidental hard breaks with the error above, it creates a great problem for users as the editor will fault out and I have no way yet of forcing a hard reset on only the encapsulating component.

I'm sure there are issues with my code, but it's been a bit rushed.

I am either running into this error, or another that states `cannot 'getLength' of undefined`. I'm assuming this is checking for cursor position inside of a block that has been removed?

!(https://preview.ibb.co/iE0SgF/draft_error.png)

The version in the picture is the implemented version which varies slightly, but not crucially.
The general codebase is here: (https://github.com/Robert-Fairley/draftjs-litho-editor)
And I've got a demo of it here: (https://robert-fairley.github.io/draftjs-litho-editor/)
You won't get an error dialog in that version yet, but it will happily flood your console for you. 😛 

It's not really _released_, but figured I'd put it out there anyway.

**What is the expected behavior?**
Ideally, no error thrown. Or if an error is thrown but the editor can persist in functioning or at least handle an isolated re-render or reset that doesn't require reloading the entire page (it contains other fields that the user would lose if they had filled them out prior to the editor breaking.)

I can share the fully implemented version on a more private basis. I'm a little bound by the difficult navigation of large-company copyright/intellectual property issues.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Current. Have only used the current version. Every browser. Only tested macOS so far.

Any help or insight is appreciated! I'd like to be able to package and release it in the end.

**Comment by ouchxp** [comment]
Having the same issue here, reproduced on draftjs.org as well.
```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at removeChild (https://cdnjs.cloudflare.com/ajax/libs/react/15.0.1/react.js:1271:14)
    at Object.processUpdates (https://cdnjs.cloudflare.com/ajax/libs/react/15.0.1/react.js:1352:11)
    at Object.dangerouslyProcessChildrenUpdates (https://cdnjs.cloudflare.com/ajax/libs/react/15.0.1/react.js:7829:27)
    at Object.wrapper [as processChildrenUpdates] (https://cdnjs.cloudflare.com/ajax/libs/react/15.0.1/react.js:12403:21)
    at processQueue (https://cdnjs.cloudflare.com/ajax/libs/react/15.0.1/react.js:11712:29)
    at ReactDOMComponent._updateChildren (https://cdnjs.cloudflare.com/ajax/libs/react/15.0.1/react.js:11889:9)
    at ReactDOMComponent.updateChildren (https://cdnjs.cloudflare.com/ajax/libs/react/15.0.1/react.js:11837:12)
    at ReactDOMComponent._updateDOMChildren (https://cdnjs.cloudflare.com/ajax/libs/react/15.0.1/react.js:7175:12)
    at ReactDOMComponent.updateComponent (https://cdnjs.cloudflare.com/ajax/libs/react/15.0.1/react.js:7021:10)
    at ReactDOMComponent.receiveComponent (https://cdnjs.cloudflare.com/ajax/libs/react/15.0.1/react.js:6977:10)```

**Comment by Robert-Fairley** [comment]
Thanks for the confirmation! I was worried it was just my implementation. At the surface it appears to be an issue of the editor state falling out of sync with the DOM -- but I haven't had the chance to dive deep enough to really thoroughly diagnose the problem. But this wouldn't surprise me with all of the commentary on `content editable` blocks.

**Comment by nburt** [comment]
Having the same issue as well. I've been having trouble trying to reproduce this locally but wanted to chime in that at least for us it seems to only be happening in Chrome (Desktop and Mobile versions)

**Comment by ouchxp** [comment]
I reproduce that just by adding like 100 lines to the editor, then select the text, type something and click inside and outside of the editor in a crazy speed.
![apr-18-2017 10-40-31](https://cloud.githubusercontent.com/assets/1253729/25107455/8983e41a-2423-11e7-8e68-f58087ed930c.gif)

**Comment by ouchxp** [comment]
Still not finding the cause after digging through some code, but it should be related to this part https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/editOnBeforeInput.js#L113
My finding is, somehow the `editOnBeforeInput` doesn't always works correctly when typing with some text being selected. 

My guess is this lead to have DOM and state not synchronized, DOM node deleted due to `editOnBeforeInput` failed to stop the native operation. When comes to render the new state, react will try to delete this non-exist node and then fail.

**Comment by ArkadiyLis** [comment]
See this solution. https://github.com/facebook/draft-js/issues/1320#issuecomment-476509968

**Comment by rahul1995** [comment]
Why is that fix not handling auto-scroll? Check this: https://github.com/samuelmeuli/mini-diary/issues/47
