### ISSUE TITLE
gulpfile breaking npm install

### ISSUE THREAD

**Issue by nilaratna** [facebook/draft-js#1650]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`npm install` fails at the gulp step when installing dependencies

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
Tried this with `npm` versions `4.0.2`, `3.10.10`. 
```draft-js git:(master) npm install

> draft-js@0.10.5 prepublish /Users/pritikanilaratna/Sites/draft-js
> npm run build


> draft-js@0.10.5 build /Users/pritikanilaratna/Sites/draft-js
> gulp

/Users/pritikanilaratna/Sites/draft-js/gulpfile.js:107
        ),
        ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/Users/pritikanilaratna/Sites/draft-js/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/pritikanilaratna/Sites/draft-js/node_modules/liftoff/index.js:198:16)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! draft-js@0.10.5 build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the draft-js@0.10.5 build script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the draft-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs draft-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls draft-js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pritikanilaratna/Sites/draft-js/npm-debug.log

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! draft-js@0.10.5 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the draft-js@0.10.5 prepublish script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the draft-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs draft-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls draft-js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pritikanilaratna/Sites/draft-js/npm-debug.log```

**What is the expected behavior?**
`npm install` completes installing dependencies correctly

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

**Comment by thibaudcolas** [comment]
Hey @nilaratna, it seems that this trailing comma got introduced in #1644. This won't work in Node 6 (which you're using). I can see that the Travis build is using Node 8 (which uses v8 5.8, so does support those types of trailing commas) – if you switch to Node 8 it should work fine.

**Comment by nilaratna** [comment]
@thibaudcolas Awesome, that worked. I was thrown off by the versions listed in package.json. Is there a plan to update so as to indicate that `6.x` is not supported?
```
"devEngines": {
    "node": "6.x || 8.x || 9.x",
    "npm": "2.x || 3.x || 5.x"
  }
```

**Comment by thibaudcolas** [comment]
Great! Good question :) I have submitted a PR going in that direction (#1652), we'll see what happens next.
