### ISSUE TITLE
Clone and npm run build give gulp error

### ISSUE THREAD

**Issue by jakcharlton** [facebook/draft-js#171]
I cloned the repo, did npm install and npm run build - the second command fails with :+1: 

```
> draft-js@0.1.0 build /Users/jak/Documents/code/react/draft-js
> gulp

/Users/jak/Documents/code/react/draft-js/node_modules/fbjs-scripts/gulp/check-dependencies.js:50
          failures.push({name, current, requested});
                             ^
SyntaxError: Unexpected token ,
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jak/Documents/code/react/draft-js/gulpfile.js:25:29)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! draft-js@0.1.0 build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the draft-js@0.1.0 build script 'gulp'.
npm ERR! This is most likely a problem with the draft-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls draft-js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jak/Documents/code/react/draft-js/npm-debug.log
```

**Comment by hellendag** [comment]
cc @zpao @spicyj

**Comment by jakcharlton** [comment]
Further tests:

I updated everything, npm up to 3.8, now npm outdated -g --depth=0 reports nothing outdated

Same error happens

**Comment by jakcharlton** [comment]
Fixed, turns out node was out of date

In this case node was installed via homebrew, so took a lot of homebrew update/doctor/link commands to get the latest downloaded

**Comment by zpao** [comment]
Yea, we require node 4+ to build. And the script which checks you have the right dependencies is written to depend on node 4 as well.

We should probably add that to the readme so we can point somewhere when this happens again.
