### ISSUE TITLE
Selecting lines of empty text and using RichTextUtils to toggle inline styles in Windows 7 IE11 does not work

### ISSUE THREAD

**Issue by gdehmlow** [facebook/draft-js#1742]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

If you select any amount of empty lines of text in IE11, then toggle a style using RichTextUtils, it pukes with this stack trace:

```
TypeError: Unable to get property 'set' of undefined or null reference
  at chars(./node_modules/draft-js/lib/CharacterMetadata.js:67:1)
  at Anonymous function(./node_modules/draft-js/lib/ContentStateInlineStyle.js:58:1)
  at Anonymous function(./node_modules/draft-js/node_modules/immutable/dist/immutable.js:3004:29)
  at value(./node_modules/draft-js/node_modules/immutable/dist/immutable.js:2687:27)
  at ft.prototype.__iterate(./node_modules/draft-js/node_modules/immutable/dist/immutable.js:2193:1)
  at Tt.prototype.__iterate(./node_modules/draft-js/node_modules/immutable/dist/immutable.js:2686:1)
  at r.__iterateUncached(./node_modules/draft-js/node_modules/immutable/dist/immutable.js:3003:1)
  at seqIterate(./node_modules/draft-js/node_modules/immutable/dist/immutable.js:606:1)
  at U.prototype.__iterate(./node_modules/draft-js/node_modules/immutable/dist/immutable.js:276:1)
  at iter(./node_modules/draft-js/node_modules/immutable/dist/immutable.js:4374:1)
  at Anonymous function(./node_modules/draft-js/node_modules/immutable/dist/immutable.js:2639:1)
  at v(./node_modules/draft-js/node_modules/immutable/dist/immutable.js:1342:1)
  at OrderedMap(./node_modules/draft-js/node_modules/immutable/dist/immutable.js:2639:41)
  at reify(./node_modules/draft-js/node_modules/immutable/dist/immutable.js:3554:1)
  at newBlocks(./node_modules/draft-js/node_modules/immutable/dist/immutable.js:4394:1)
  at modifyInlineStyle(./node_modules/draft-js/lib/ContentStateInlineStyle.js:38:1)
  at o.remove(./node_modules/draft-js/lib/ContentStateInlineStyle.js:27:1)
  at b.removeInlineStyle(./node_modules/draft-js/lib/DraftModifier.js:133:1)
  at this(./node_modules/draft-js/lib/RichTextEditorUtil.js:266:1)
  at func(./src/scripts/presentation/components/customer/composition/lib/draft/draft_styles_menu.jsx:13:5)
  // ...
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

![draftie11selectbug](https://user-images.githubusercontent.com/850025/39265954-7ee88798-487d-11e8-9a49-9be76c46973b.gif)

**What is the expected behavior?**

It should not throw an error and it should properly apply the inline style changes to the lines of text that have text

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

Windows 7 IE11 with latest version of draft

**Comment by mrkev** [comment]
Is this still an issue @gdehmlow? I think this might have been fixed, but don't have a Windows VM with IE11 handy to check. If you do, let me know.
