### ISSUE TITLE
npm run build fails with a syntax error

### ISSUE THREAD

**Issue by lerouxb** [facebook/draft-js#176]
I'm running node v4.3.2, installed via nvm. I did a npm install, it complained that babel and cover prefers global, I then installed both those versions manually with -g, I ran npm run build and it gives me this:

```bash
$ npm run build

> draft-js@0.1.0 build /Users/leroux/src/draft-js
> gulp

/Users/leroux/src/draft-js/node_modules/gulp-util/node_modules/lodash.template/node_modules/lodash._isiterateecall/index.js:80
});
 ^

SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/leroux/src/draft-js/node_modules/gulp-util/node_modules/lodash.template/index.js:12:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/leroux/.nvm/versions/node/v4.3.2/bin/node" "/Users/leroux/.nvm/versions/node/v4.3.2/bin/npm" "run" "build"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! draft-js@0.1.0 build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the draft-js@0.1.0 build script 'gulp'.
npm ERR! This is most likely a problem with the draft-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls draft-js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/leroux/src/draft-js/npm-debug.log
```

Any ideas? I really want to try this out..

**Comment by lerouxb** [comment]
Solved with the good old "`rm -rf node_modules` and start over" trick.

**Comment by zpao** [comment]
`npm update` probably would have done it too. Looks like a bad version of lodash got published and you hit npm at just the wrong time :/
