### ISSUE TITLE
Building fails (node 8.11.3, npm 6.2.0, ubuntu 18.04)

### ISSUE THREAD

**Issue by riverfr0zen** [facebook/draft-js#1825]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
fails to build, can't view examples

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
followed steps in documentation to build and see examples

**What is the expected behavior?**
build succeeds and can view examples

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
These are the versions I tried:
* master
* v.0.10.0
* v.0.10.5

I get some different errors depending on which version of node or npm I use, but the following is what I get for node 8.11.3 and npm 6.2.0:

```
[16:29:03] Starting 'modules'...
[16:29:03] Starting 'flow'...

events.js:183
      throw er; // Unhandled 'error' event
      ^
SyntaxError: /home/irf/draft-js/src/component/base/DraftEditor.react.js: Missing class properties transform.
  68 |  */
  69 | class DraftEditor extends React.Component<DraftEditorProps, State> {
> 70 |   static defaultProps: DraftEditorDefaultProps = {
     |   ^
  71 |     blockRenderMap: DefaultDraftBlockRenderMap,
  72 |     blockRendererFn: emptyFunction.thatReturnsNull,
  73 |     blockStyleFn: emptyFunction.thatReturns(''),
    at File.buildCodeFrameError (/home/irf/draft-js/node_modules/babel-core/lib/transformation/file/index.js:427:15)
    at NodePath.buildCodeFrameError (/home/irf/draft-js/node_modules/babel-traverse/lib/path/index.js:140:26)
    at ClassTransformer.pushBody (/home/irf/Dropbox/PublicPhotos/htdocs/irfanbaig.com/www.react/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:262:20)
    at ClassTransformer.buildBody (/home/irf/Dropbox/PublicPhotos/htdocs/irfanbaig.com/www.react/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:229:10)
    at ClassTransformer.run (/home/irf/Dropbox/PublicPhotos/htdocs/irfanbaig.com/www.react/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:143:10)
    at PluginPass.ClassExpression (/home/irf/Dropbox/PublicPhotos/htdocs/irfanbaig.com/www.react/node_modules/babel-plugin-transform-es2015-classes/lib/index.js:48:60)
    at newFn (/home/irf/draft-js/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/home/irf/draft-js/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/irf/draft-js/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/irf/draft-js/node_modules/babel-traverse/lib/path/context.js:105:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! draft-js@0.10.5 build: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the draft-js@0.10.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/irf/.npm/_logs/2018-07-29T20_29_04_185Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! draft-js@0.10.5 prepublish: `npm run build`
npm ERR! Exit status 1
```
Incidentally, is there any place online to see the latest examples instead of having to build it?

**Comment by riverfr0zen** [comment]
Nevermind, it appears I beguiled myself with some symlinking and had installed this under another node project hierarchy. Issue was resolved by moving it out of the hierarchy.
