### ISSUE TITLE
Safari Crash When Using `whitespace: no-wrap`

### ISSUE THREAD

**Issue by mpeterson2** [facebook/draft-js#2011]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using Safari and `whitespace: nowrap` (as suggested in #657) causes an error thrown when the user inputs any non-space character than a space. DraftJS attempts to fix the selection state, but Safari throws an error:

```
IndexSizeError: The index is not in the allowed range.
  at extend([native code])
  at addFocusToSelection(./node_modules/draft-js/lib/setDraftEditorSelection.js:192:1)
  at setDraftEditorSelection(./node_modules/draft-js/lib/setDraftEditorSelection.js:154:1)
  at _setSelection(./node_modules/draft-js/lib/DraftEditorLeaf.react.js:87:1)
  at stateNode(./node_modules/draft-js/lib/DraftEditorLeaf.react.js:106:1)
  at ih(./node_modules/react-dom/cjs/react-dom.production.min.js:214:352)
  at Xg(./node_modules/react-dom/cjs/react-dom.production.min.js:206:39)
  at Yg(./node_modules/react-dom/cjs/react-dom.production.min.js:205:1)
  at uh(./node_modules/react-dom/cjs/react-dom.production.min.js:217:190)
  at Hd(./node_modules/react-dom/cjs/react-dom.production.min.js:86:189)
  at Nn([native code])
  at wrapped(./node_modules/raven-js/src/raven.js:352:1)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
Unfortunately I could not repro this on jsfiddle. However, I created a simple create-react-app sample project that repros: https://github.com/mpeterson2/draftjs-safari-crash

**What is the expected behavior?**
There is no crash and the selection state is set correctly

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Draft.js: 0.10.5
Browser: Safari 12.0.3
OS: OSX 10.14.3

**Comment by luisaGonzales** [comment]
Any update on this?

**Comment by kunstefix** [comment]
I experienced the same issue when trying to override white-space with `white-space:normal`.
