### ISSUE TITLE
Documentation is hard to understand

### ISSUE THREAD

**Issue by daryn-k** [facebook/draft-js#2037]
I watched Isaac Hellendag's presentation. It was very interesting and promising. But after reading the documentation I'm stucking. Everything looks like a rocket-science. It's so crazy, tricky and hard to understand. Please, simplify it somehow.

Some code even doesn't work itself.

```
const contentState = editorState.getCurrentContent();
const contentStateWithEntity = contentState.createEntity(
  'LINK',
  'MUTABLE',
  {url: 'http://www.zombo.com'}
);
const entityKey = contentStateWithEntity.getLastCreatedEntityKey();
const contentStateWithLink = Modifier.applyEntity(
  contentStateWithEntity,
  selectionState,
  entityKey
);
const newEditorState = EditorState.push(editorState, { currentContent: contentStateWithLink });
```
For example, what is `selectionState`? You never mentioned about it before. How can I understand what is it and where to get it from? I read this page 100 times. It's really so tricky. Please, explain, anybody.

It would be cool if you attach some images of the structure of Editor state. Now I even can't imagine that. I tried to console.log(editorState), but it shows some crazy, messy, unreadable and huge structure. Or is it some special magic there? Or am I so stupid? Sorry for an emotional expressions.

**Comment by claudiopro** [comment]
Hi @daryn-k, thanks for your feedback. As a new maintainer still learning about this project, I can relate a lot with your comments.

While our top priority was to resume publishing new versions to npm, we know clear documentation with immediately consumable examples and in-depth tutorials for further learning make the success of an open source project.

**Comment by andrewcodes404** [comment]
Yes I agree with @claudiopro , the docs are not great and even the demo examples won't run, error on npm install
```
[14:12:28] Using gulpfile ~/Desktop/draft-js/gulpfile.js
[14:12:28] Starting 'default'...
[14:12:28] Starting 'check-dependencies'...
[14:12:28] Starting '<anonymous>'...
[14:12:28] '<anonymous>' errored after 30 ms
[14:12:28] Error: spawn yarn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[14:12:28] 'check-dependencies' errored after 32 ms
[14:12:28] 'default' errored after 35 ms
npm ERR! code ELIFECYCLE
```

**Comment by geekyme** [comment]
Checked the source code of one of the dependency that is package is relying on:
https://github.com/facebook/fbjs/blob/master/packages/fbjs-scripts/gulp/check-dependencies.js#L25

It calls `yarn`, therefore if you don't have yarn in your PATH, and missing a `yarn.lock` you will run into errors. 

The documentation is misleading to say that we should use npm install. It should be `yarn install` instead. https://github.com/facebook/draft-js/blame/master/README.md#L115

**Comment by daryn-k** [comment]
I figured out how everything works. Don't even try to understand the structure of immutable data. Convert it to raw and work with it as you want. It's very tricky, but after spending 1-2 weeks I done my own editor. But Draft Editor has many kinda bugs. For example, atomic blocks work so stupid. It put new lines before and after itself, and you can't fix it. Just convert everything to raw and remove these empty lines.

**Comment by antoniojps** [comment]
It's hard, but that's a reflection of how hard it is to create a Rich Text Editor. I've read most of the other rich text editor solutions and all have the same "complex" concepts but with other names.

The best resource I've found was this presentation available on Youtube done by Mair Swartz: https://www.youtube.com/watch?v=vOZAO3jFSHI

Also the source documentation for that presentation: https://draft-js-samples.now.sh/Home

I think the documentation is lacking in terms of custom Atomic Blocks and how to handle data conversion and storage.
