### ISSUE TITLE
Importing draftjs breaks server side rendering

### ISSUE THREAD

**Issue by asyncb** [facebook/draft-js#2142]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
By importing draftjs utils 
`import { convertToRaw, Editor, EditorState, RichUtils } from 'draft-js';`
Our app breaks. According to Next.js, the likely solution is to `require()` in componentDidMount.
DraftJS non-rendered data/logic and objects shouldn't require the DOM to exist, especially not before actually utilizing the functions (which I tried in componentDidMount). The problem is that importing draft-js requires the DOM, and I don't think it should. That logic should be part of `<Editor/>` componentWillMount/componentDidMount rather than a global script polluting the import process
```
Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
    at Object.<anonymous> (/lawyer-portal/node_modules/draft-js/node_modules/fbjs/lib/getDocumentScrollElement.js:11:72)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/lawyer-portal/node_modules/draft-js/node_modules/fbjs/lib/getScrollPosition.js:11:32)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
I don't have time for this right now

**What is the expected behavior?**
Importing draftJS utils shouldn't break SSR by accessing non-existant properties in a headless browser context.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Next.js 8.0.3
DraftJS 0.0.11 and 0.0.10

**Comment by asyncb** [comment]
Hack solution / workaround reinforces that import is the problem
This works, but with a large delay
```
  constructor(props) {
    super(props);
    this.state = {
      editorState: null,
    };
  }

  componentDidMount() {
    draftConvert = require('draft-convert');
    draftJs = require('draft-js');
    convertFromHTML = draftConvert.convertFromHTML;
    convertToRaw = draftJs.convertToRaw;
    Editor = draftJs.Editor;
    EditorState = draftJs.EditorState;
    RichUtils = draftJs.RichUtils;
    this.setState({
      editorState: this.newEditorState(this.props.initialValue),
    });
  }
```

**Comment by dobesv** [comment]
FWIW in our project we are using SSR with draft-js and it works OK, no DOM emulation layer required.  We're running it in `node`, though, not a headless browser context (whatever that is).

There must be something else about your setup that is triggering this issue.

**Comment by asyncb** [comment]
I'm not sure about the specifics, but we're using Next.js, which uses node, express, and webpack  and invokes top-level component lifecycle method "getInitialProps". Node is a headless context, and `global` is the keyword replacement for `window` which has document.

The most important evidence:
1. the stack trace `/node_modules/draft-js/node_modules/fbjs/lib/getDocumentScrollElement.js`
2. the fact that importing after didMount solves any issues
