### ISSUE TITLE
Error: jest-haste-map: Watchman crawl failed. Retrying once with node crawler.

### ISSUE THREAD

**Issue by claudiopro** [facebook/draft-js#2183]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When running `jest` in watch mode on the root directory of the project, `jest-haste-map` throws an error:

```
$ yarn test --watch
Using globally installed version of Yarn
yarn run v1.12.1
$ node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
$ cross-env NODE_ENV=test jest --watch
jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: resolve_projpath:  None of the files listed in global config root_files are present in path `/Users/procidac/Development/gh/facebook/draft-js/src` or any of its parent directories.  root_files is defined by the `/etc/watchman.json` config file and includes `.watchmanconfig`.  One or more of these files must be present in order to allow a watch. Try pulling and checking out a newer version of the project?. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.html.
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: resolve_projpath:  None of the files listed in global config root_files are present in path `/Users/procidac/Development/gh/facebook/draft-js/src` or any of its parent directories.  root_files is defined by the `/etc/watchman.json` config file and includes `.watchmanconfig`.  One or more of these files must be present in order to allow a watch. Try pulling and checking out a newer version of the project?
    at BunserBuf.<anonymous> (/Users/procidac/Development/gh/facebook/draft-js/node_modules/fb-watchman/index.js:95:23)
    at BunserBuf.emit (events.js:182:13)
    at BunserBuf.process (/Users/procidac/Development/gh/facebook/draft-js/node_modules/bser/index.js:292:10)
    at /Users/procidac/Development/gh/facebook/draft-js/node_modules/bser/index.js:247:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
Emitted 'error' event at:
    at Client.client.on.error (/Users/procidac/Development/gh/facebook/draft-js/node_modules/jest-haste-map/build/lib/WatchmanWatcher.js:130:10)
    at Client.emit (events.js:182:13)
    at BunserBuf.<anonymous> (/Users/procidac/Development/gh/facebook/draft-js/node_modules/fb-watchman/index.js:107:12)
    at BunserBuf.emit (events.js:182:13)
    at /Users/procidac/Development/gh/facebook/draft-js/node_modules/bser/index.js:249:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This is similar to https://github.com/facebook/create-react-app/issues/346

**What is the expected behavior?**
Jest starts in watch mode without errors

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
This is happening in draft-js master with Node v10.14.2

**Comment by nigelrobbins3** [comment]
I had this issue and it was because my Mac OS upgrade had removed permissions which `watchman` needed to watch files in the `Documents` directory. I went into System Preferences > Security & Privacy > Privacy > Files and Folders and manually gave `watchman` access.

Mas OS version: 10.15.1
Jest version: 22.1.4
watchman version: 4.9.0

**Comment by AmitPandya007** [comment]
at your root project location:

create a file named as **.watchmanconfig**
and add **{}** as it's file content.

I have resolved by doing this for my project.

**Comment by djamiem** [comment]
> at your root project location:
> 
> create a file named as **.watchmanconfig**
> and add **{}** as it's file content.
> 
> I have resolved this by doing this for my project.
> and @nigelrobbins3 answer also helped to solve it.

I think this means you accidentally ran 'yarn test' in root and not in /employee-portal-mobile. If you run in that project folder you will not see the .watchmanconfig error as the jest tests will be running in the correct context.

**Comment by jleach** [comment]
Based on @nigelrobbins3 remark above I ran `brew uninstall watchman` and `brew install watchman` to fix the problem.

**Comment by PauloHCardosoN** [comment]
Don't install your application in the `Documents` root directory, put it in a folder. It worked for me.

No
![Captura de Tela 2020-07-24 às 23 07 15](https://user-images.githubusercontent.com/59656828/88447549-6d771a80-ce02-11ea-9154-9dfc2ce083a3.png)

Yes
![Captura de Tela 2020-07-24 às 23 08 03](https://user-images.githubusercontent.com/59656828/88447564-897abc00-ce02-11ea-9f62-1dff54ed5bb1.png)

**Comment by jasonwr** [comment]
> Based on @nigelrobbins3 remark above I ran `brew uninstall watchman` and `brew install watchman` to fix the problem.

```brew reinstall watchman```

**Comment by jbesraa** [comment]
Having the same issue, none of the above worked
Mac 10.15.6
Node 14

**Comment by Ogala** [comment]
I deleted the existing `.watchmanconfig` and created another one. Problem solved.

**Comment by AdamGerthel** [comment]
> Having the same issue, none of the above worked Mac 10.15.6 Node 14

Same here, but am running MacOS 12 (Monterey). Did you find a solution?

**Comment by zrichardson8039** [comment]
Mine was due to watchman caching data from other react-native projects. 

After I ran `yarn clean` (i.e. `rm -rf $TMPDIR/react-* && watchman watch-del-all && yarn cache clean`), the error went away.

**Comment by Enricopv** [comment]
@zrichardson8039 solution did the trick for me. I'm working with react-native in a yarn workspaces monorepo.

**Comment by Dajust** [comment]
Running `watch-del-all && yarn cache clean && react-native start --reset-cache` solved it for me!

**Comment by engrwaqasali** [comment]
For expo users
dont use npm start or yarn start
simply "expo start" will solve it

**Comment by shoopi12** [comment]
Related [issue](https://github.com/facebook/watchman/issues/1030)

**Comment by gamble2020** [comment]
I literally tried everything on this thread but nothing worked on my Mac M1. To fix I moved my project out of "Documents" and into my mac  user home directory.

**Comment by AnuragHarod** [comment]
I went into System Preferences > Security & Privacy > Privacy > Files and Folders and manually gave access to the following for react-native projects.
- watchman
- Android Studio
- Visual Studio Code(If running command from VS code)

**Comment by sahilbakoru** [comment]
@gamble2020  thanks. nothing was working but your solution worked.

**Comment by kaushal-yadav** [comment]
I tried to just uninstall watchman and it worked for me.
`brew uninstall watchman`

**Comment by hetramjanghu** [comment]
> I tried to just uninstall watchman and it worked for me. `brew uninstall watchman`

Thank You
it`s help full me

**Comment by dev-event** [comment]
@kaushal-yadav It helped me too. Why is that?

**Comment by shoopi12** [comment]
If you uninstall watchman you don't get any of its benefits..

**Comment by dev-event** [comment]
yes

**Comment by kaushal-yadav** [comment]
> @kaushal-yadav It helped me too. Why is that?

The thing that I found 

`You're running watchman as root but the state dir, which may contain trigger definitions and thus allow spawning arbitrary commands, is not owned by root. This is a security issue and thus watchman is refuses to start. 

It wants full disk access if you give that it will work. But we don't want to give full disk access `

**Comment by nguyenthanh1205tb** [comment]
> I tried to just uninstall watchman and it worked for me. `brew uninstall watchman`

thanks! its works for me

**Comment by dev-event** [comment]
I found a solution. Move the folder from the project to the directory: Users/shared folde
<img width="140" alt="Снимок экрана 2022-06-21 в 11 35 51" src="https://user-images.githubusercontent.com/56742002/174755916-a72afce4-8a85-408e-93c1-814425eabcfd.png">
r

**Comment by gersonmontenegroepam** [comment]
My computer is controlled by the company who I work for, and I'm not able to add watchman to the system preferences/Security and privacy/Privacy.... , so I moved the project to /Users/myusername/ ...and it started to work.

**Comment by manirikhi** [comment]
Hope this will be helpful. worked for me.

You should move the entire project directory outside of the Documents or Download directory for mac

https://github.com/facebook/watchman/issues/977

**Comment by shazimajaz1** [comment]
So just to add more context to this. I had a similar issue in the react native project. It turns out this started when I was trying to install watchman to eject the project from expo. I uninstalled the watchman and did not re-install it. That worked for me and expo started working again for me!

**Comment by ankush-xebia** [comment]
first run `watchman watch-del-all `
then run `watchman shutdown-server`
and finally `npx react-native start`

**Comment by rishiankush** [comment]
First run `watchman watch-del-all`
then run `watchman shutdown-server`

**Comment by saronlujan** [comment]
> Running `watch-del-all && yarn cache clean && react-native start --reset-cache` solved it for me!

`watchman watch-del-all && yarn cache clean && react-native start --reset-cache` work for me!

**Comment by josephflerime** [comment]
In my case, I have an m1 MacBook pro, I had to just uninstall watchman with brew uninstall watchman and it worked.

**Comment by slhck** [comment]
In case reinstalling `watchman` on macOS does not work, do:

```
brew uninstall watchman
killall watchman
brew install watchman
```

This will prompt for access to the `Documents` folder on the next launch of watchman, which should resolve the permissions issue.

**Comment by mohit2605** [comment]
Just Restart your system. Helped in my case.

**Comment by hokimtam** [comment]
> Documents

saved my life. thanks.

**Comment by hokimtam** [comment]
> I deleted the existing `.watchmanconfig` and created another one. Problem solved.

Saved my life. Thanks.

**Comment by nemwiper** [comment]
> none of the above answers worked for me. Restarted my Mac and it worked.

Yes, restarted my Mac worked for me also.
At login it asked Watchman for permission in the project folder. Odd.

**Comment by whatapangolin** [comment]
Mac M1
Give full disk access to watchman solved my prob.

**Comment by mucahitkok** [comment]
restart my mac m1

**Comment by patrickmuhi** [comment]
First run `watchman watch-del-all`
then run `watchman shutdown-server` fixed my issue

**Comment by codershona** [comment]
> scripts



> > @kaushal-yadav It helped me too. Why is that?
> 
> The thing that I found
> 
> ```
> You're running watchman as root but the state dir, which may contain trigger definitions and thus allow spawning arbitrary commands, is not owned by root. This is a security issue and thus watchman is refuses to start. 
> 
> It wants full disk access if you give that it will work. But we don't want to give full disk access 
> ```

It worked for me by uninstalling watchman in macbook pro m1. I was first all install watchman by running brew install watchman and then give full disk access watchman and my terminal including VSC editor in the security and privacy of system preferences. But it was  not working. Then once i run brew uninstall watchman now after restarting my terminal i run npm test and everything is working fine.

**Comment by KrisLau** [comment]
1. watchman watch-del-all
2. watchman shutdown-server
 worked for me

**Comment by imamrobani** [comment]
> First run `watchman watch-del-all` then run `watchman shutdown-server`

I got this issue after the update watchman.
so I try this solution. this work for me, thanks.

**Comment by benhurley** [comment]
> 

This worked for me too, thanks!

**Comment by benhurley** [comment]
> 1. `watchman watch-del-all`
> 2. `watchman shutdown-server`
> 
> Worked for me

This worked for me too, thanks!
