### ISSUE TITLE
when npm run build : events.js:154  throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by FakhruddinAbdi** [facebook/draft-js#226]
I have cloned draft-js and after npm i, at the first attemp of npm run build , it came across the error below :

 ```
Faxra-mac:draft-js abdi.fakhruddin$ sudo npm run build 

> draft-js@0.3.0 build /Users/fakhruddinabdi/WebstormProjects/archive/draft-js
> gulp

[10:57:57] Using gulpfile ~/WebstormProjects/archive/draft-js/gulpfile.js
[10:57:57] Starting 'default'...
[10:57:57] Starting 'check-dependencies'...
[10:57:59] Finished 'check-dependencies' after 2.83 s
[10:57:59] Starting 'clean'...
[10:57:59] Finished 'clean' after 4.61 ms
[10:57:59] Starting 'modules'...

events.js:154
      throw er; // Unhandled 'error' event
      ^
ReferenceError: [BABEL] /Users/fakhruddinabdi/WebstormProjects/archive/draft-js/src/Draft.js: Unknown option: /Users/fakhruddinabdi/WebstormProjects/.babelrc.presets
    at Logger.error (/Users/fakhruddinabdi/WebstormProjects/archive/draft-js/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/fakhruddinabdi/WebstormProjects/archive/draft-js/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/Users/fakhruddinabdi/WebstormProjects/archive/draft-js/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/fakhruddinabdi/WebstormProjects/archive/draft-js/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/fakhruddinabdi/WebstormProjects/archive/draft-js/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/Users/fakhruddinabdi/WebstormProjects/archive/draft-js/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/fakhruddinabdi/WebstormProjects/archive/draft-js/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/fakhruddinabdi/WebstormProjects/archive/draft-js/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at DestroyableTransform._transform (/Users/fakhruddinabdi/WebstormProjects/archive/draft-js/node_modules/gulp-babel/index.js:30:20)
    at DestroyableTransform.Transform._read (/Users/fakhruddinabdi/WebstormProjects/archive/draft-js/node_modules/readable-stream/lib/_stream_transform.js:159:10)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.7.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! draft-js@0.3.0 build: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the draft-js@0.3.0 build script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the draft-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs draft-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls draft-js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/fakhruddinabdi/WebstormProjects/archive/draft-js/npm-debug.log
```

**Comment by FakhruddinAbdi** [comment]
#https://github.com/babel/babel-loader/issues/132

**Comment by FakhruddinAbdi** [comment]
https://github.com/babel/babel-loader/issues/132
