### ISSUE TITLE
Trouble running the examples from the docs

### ISSUE THREAD

**Issue by florianmartens** [facebook/draft-js#2306]
I am trying to run the examples from this repo.

As far as I could tell from the repo, I thought that I could run:

`git clone <<draft-js-repo>>`
`sudo npm i`

After this I thought, I could just use the browser to go on the html pages. However, on `sudo npm i` I am getting an error:

```
[13:49:37] Using gulpfile ~/Code/tutorials/draft-js-expl/draft-js/gulpfile.js
[13:49:37] Starting 'default'...
[13:49:37] Starting 'check-dependencies'...
[13:49:37] Starting '<anonymous>'...
[13:49:37] '<anonymous>' errored after 26 ms
[13:49:37] Error: spawn yarn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[13:49:37] 'check-dependencies' errored after 27 ms
[13:49:37] 'default' errored after 29 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! draft-js@0.11.4 build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the draft-js@0.11.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/florianmartens/.npm/_logs/2020-01-17T12_49_37_841Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! draft-js@0.11.4 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the draft-js@0.11.4 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/florianmartens/.npm/_logs/2020-01-17T12_49_37_867Z-debug.log
```

What I am doing wrong. How can I get the examples to work here? Thanks!

**Comment by florianmartens** [comment]
It works when using yarn.

**Comment by claudiopro** [comment]
Hi @florianmartens, that's right - npm is not officially supported although the README states otherwise. What versions of `node` and `npm` are you using for our reference?

**Comment by florianmartens** [comment]
Hey @claudiopro,

thanks for the reply. I am using npm@6.4.1 and node@10.14.0.
