### ISSUE TITLE
ReferenceError: Node is not defined

### ISSUE THREAD

**Issue by hallya** [facebook/draft-js#2390]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When testing component using editor, we get this error:

```
     ReferenceError: Node is not defined
      at isElement (node_modules/draft-js/lib/isElement.js:18:28)
      at isHTMLBRElement (node_modules/draft-js/lib/isHTMLBRElement.js:20:10)
      at ContentBlocksBuilder._addBreakNode (node_modules/draft-js/lib/convertFromHTMLToContentBlocks.js:557:10)
      at ContentBlocksBuilder._toBlockConfigs (node_modules/draft-js/lib/convertFromHTMLToContentBlocks.js:461:14)
      at ContentBlocksBuilder._toBlockConfigs (node_modules/draft-js/lib/convertFromHTMLToContentBlocks.js:408:52)
      at ContentBlocksBuilder.addDOMNode (node_modules/draft-js/lib/convertFromHTMLToContentBlocks.js:309:82)
      at convertFromHTMLToContentBlocks (node_modules/draft-js/lib/convertFromHTMLToContentBlocks.js:761:63)
      at e.t.initEditorState (.tmp/mocha-webpack/1587631927260/main.js:1:25724)
      at new e (.tmp/mocha-webpack/1587631927260/main.js:1:26757)
      at constructClassInstance (node_modules/react-dom/cjs/react-dom.development.js:11448:18)
      at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:13145:7)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:13825:14)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:15864:12)
      at workLoop (node_modules/react-dom/cjs/react-dom.development.js:15903:24)
      at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:15943:7)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:16561:22)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:16483:7)
      at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:16455:3)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:16355:5)
      at scheduleWork$1 (node_modules/react-dom/cjs/react-dom.development.js:16219:11)
      at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:16786:3)
      at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:16813:10)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:16840:10)
      at ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:17123:3)
      at /Users/lucien/CloudStation/WebWork/qare/front/node_modules/react-dom/cjs/react-dom.development.js:17263:14
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:16680:10)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:17259:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:17318:12)
      at render (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:429:26)
      at fn (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:343:12)
      at Object.wrapAct [as render] (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:415:16)
      at new render (node_modules/enzyme/src/ReactWrapper.js:115:16)
      at mount (node_modules/enzyme/src/mount.js:10:10)
      at global.mountWithIntl (__tests__/unit/setup.js:88:3)
      at Context.<anonymous> (.tmp/mocha-webpack/1587631927260/main.js:1:30975)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a 
minimal demo of the problem. You can use this jsfiddle to get started:**

#### index.spec.tsx
```
import React from 'react';
import { expect } from 'chai';
import sinon from 'sinon';
import { mount, ReactWrapper } from 'enzyme';
import ConfidentialNotes from '.';

describe('ConfidentialNotes', () => {
  let wrapper: ReactWrapper;
  let handleChangeSpy: sinon.SinonSpy;

  beforeEach(() => {
    handleChangeSpy = sinon.spy();
    wrapper = mount(
      <ConfidentialNotes
        defaultValue={'Test'}
        handleChange={handleChangeSpy}
      />
    );
  });

  it('should render', () => {
    expect(wrapper.isEmptyRender()).to.be.false;
  });
});
```

#### index.tsx

```
import React from 'react';
import {
  Editor as DraftJsEditor,
} from 'draft-js';

type Props = {};

const ConfidentialNotes = (props: Props) => {
  return (
          <DraftJsEditor
            ref={this.setEditor}
            editorState={this.state.editorState}
            onChange={this.onChange}
            handleKeyCommand={this.handleKeyCommand}
            keyBindingFn={this.keyBindingFn}
          />
  );
};

export default ConfidentialNotes;
```

**What is the expected behavior?**
Being able to mount any component using Editor without errors

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
`"draft-js": "^0.11.5",`

**Comment by ankeshdamahe** [comment]
I am also facing same problem any solution for this
