### ISSUE TITLE
npm build throws gulp error

### ISSUE THREAD

**Issue by Johnson444** [facebook/draft-js#2506]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

npm build script throws a gulp error

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/gmertk/e61z7nfa/.**

git clone https://github.com/facebook/draft-js.git
npm install
npm run build

[15:00:09] Using gulpfile ~/Documents/packages/draft-js/gulpfile.js
[15:00:09] Starting 'default'...
[15:00:09] Starting 'check-dependencies'...
[15:00:09] Starting '<anonymous>'...
[15:00:09] '<anonymous>' errored after 32 ms
[15:00:09] Error: spawn yarn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[15:00:09] 'check-dependencies' errored after 35 ms
[15:00:09] 'default' errored after 37 ms

**Comment by mrkev** [comment]
The build does seem to be broken... not sure why. Thanks for pointing this out 👍

**Comment by mrkev** [comment]
Oh derp. We need to update the readme— the build/install should be done with yarn (hence, there's a yarn lock file, no npm lockfile)

I need to check the CI and see what's going on there, but as far as this issue, it'll work with yarn. I just built it on my machine.
