### ISSUE TITLE
expected "5.6.0" to satisfy "4.x"

### ISSUE THREAD

**Issue by guocheng** [facebook/draft-js#34]
I got this error:

```
11:18 $ npm run build

> draft-js@0.1.0 prebuild /Users/cheng/Dev/draft-js
> node node_modules/fbjs-scripts/node/check-dev-engines.js package.json


assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: Current node version is not supported for development, expected "5.6.0" to satisfy "4.x".
    at Object.<anonymous> (/Users/cheng/Dev/draft-js/node_modules/fbjs-scripts/node/check-dev-engines.js:39:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
```

The line which caused the error:

```
node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
```

My node version is 5.6.0 (I am using nvm) which is what the error message expects:

```
11:20 $ node --version
v5.6.0
```

Any ideas of what I missed?

Thanks.

**Comment by Aweary** [comment]
I believe the error is saying that your version, `5.6.0` was expected to satisfy `4.x`, meaning you need be using version `4.x` for development.

**Comment by guocheng** [comment]
Got it, thx
