### ISSUE TITLE
Unable to build draft-js examples

### ISSUE THREAD

**Issue by vikramjakkampudi** [facebook/draft-js#914]
Trying to build draft-js examples...
in Ubuntu 14 with nodev4.2.6 
got this error while build

> draft-js@0.10.0 build /home/ubuntu/draft-js-0.10-stable
> gulp

[11:09:11] Using gulpfile ~/draft-js-0.10-stable/gulpfile.js
[11:09:11] Starting 'default'...
[11:09:11] Starting 'check-dependencies'...
[11:09:15] 'check-dependencies' errored after 3.5 s
[11:09:15] Error in plugin 'check-dependencies'
Message:
    npm broke
[11:09:15] 'default' errored after 3.5 s
[11:09:15] Error in plugin 'run-sequence(check-dependencies)'
Error
    at finish (/home/ubuntu/draft-js-0.10-stable/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/home/ubuntu/draft-js-0.10-stable/node_modules/run-sequence/index.js:67:4)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/home/ubuntu/draft-js-0.10-stable/node_modules/orchestrator/index.js:264:8)
    at /home/ubuntu/draft-js-0.10-stable/node_modules/orchestrator/index.js:275:23
    at finish (/home/ubuntu/draft-js-0.10-stable/node_modules/orchestrator/lib/runTask.js:21:8)
    at DestroyableTransform.<anonymous> (/home/ubuntu/draft-js-0.10-stable/node_modules/orchestrator/lib/runTask.js:52:4)
    at DestroyableTransform.f (/home/ubuntu/draft-js-0.10-stable/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at emitOne (events.js:82:20)

npm ERR! Linux 3.13.0-106-generic
npm ERR! argv "/home/ubuntu/node-v4.2.6-linux-x64/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! draft-js@0.10.0 build: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the draft-js@0.10.0 build script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the draft-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs draft-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls draft-js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/draft-js-0.10-stable/npm-debug.log

**Comment by thebeastygecko** [comment]
I have the same problem on Mac OSX, where node and npm are installed and updated with brew:
`npm ERR! node v7.3.0
npm ERR! npm  v4.0.5
`

**Comment by davidchang** [comment]
strange. i just tried, with node v6.3.1/nvm v3.10.3 and couldn't repro..

**Comment by Arinteck** [comment]
I also have the same problem with node v7.4.0 & npm v4.0.5

**Comment by ribalba** [comment]
I get the same with v7.4.0 but if I downgrade to v6.9.4 everything works fine. 

The error can be traced down to ```npm outdated  --json --long``` returning ```0``` in version 6 and for some reason ```1``` in version 7. This can be found in https://github.com/facebook/fbjs/blob/master/packages/fbjs-scripts/gulp/check-dependencies.js#L38

I will post submit an issue in that repo.

**Comment by JeremyIglehart** [comment]
I have the same:

```
$ npm run build

> draft-js@0.9.0 build /Users/jeremy/Documents/Programming/draft-js
> gulp

[02:06:30] Using gulpfile ~/Documents/Programming/draft-js/gulpfile.js
[02:06:30] Starting 'default'...
[02:06:30] Starting 'check-dependencies'...
[02:06:32] 'check-dependencies' errored after 2.35 s
[02:06:32] Error in plugin 'check-dependencies'
Message:
    npm broke
[02:06:32] 'default' errored after 2.36 s
[02:06:32] Error in plugin 'run-sequence(check-dependencies)'
Error
    at finish (/Users/jeremy/Documents/Programming/draft-js/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/Users/jeremy/Documents/Programming/draft-js/node_modules/run-sequence/index.js:67:4)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/jeremy/Documents/Programming/draft-js/node_modules/orchestrator/index.js:264:8)
    at /Users/jeremy/Documents/Programming/draft-js/node_modules/orchestrator/index.js:275:23
    at finish (/Users/jeremy/Documents/Programming/draft-js/node_modules/orchestrator/lib/runTask.js:21:8)
    at DestroyableTransform.<anonymous> (/Users/jeremy/Documents/Programming/draft-js/node_modules/orchestrator/lib/runTask.js:52:4)
    at DestroyableTransform.f (/Users/jeremy/Documents/Programming/draft-js/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at emitOne (events.js:101:20)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! draft-js@0.9.0 build: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the draft-js@0.9.0 build script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the draft-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs draft-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls draft-js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jeremy/Documents/Programming/draft-js/npm-debug.log
```

**Comment by Yukaii** [comment]
Build failed with node version 6.9.1 and npm 4.1.1. Downgrade npm to version `3.10.10` and get working now.

```bash
npm install npm@3.10.10 -g
```

**Comment by xiguaaxigua** [comment]
same error with `node: 7.4.0 & npm:4.1.2`;
working with `node: 6.9.4 & npm 3.10.10`;

**Comment by goodhyun** [comment]
node 7.3.0 and npm 3.10.10 was safe too.

**Comment by OlivierCo** [comment]
I had the same problem, I just downgraded node to 6.9.4 with [n](https://github.com/tj/n) and it works like a charm after.

**Comment by invegat** [comment]
Edited my local /fbjs-scripts/gulp/check-dependencies.js L38 to 
- if (code !== 0 && code !== 1) {

and changed package.json 
-   "devEngines": {
    "node": "4.x || 6.x || 7.x",
    "npm": "2.x || 3.x || 4.x"
  },

was able to run the package.json scripts

Was unable to run the webside folder project in Windows 10, "npm start" errored out.  Got it working on 
the Windows 10 Bash Shell Linex with
-   [Xming](https://www.howtogeek.com/261575/how-to-run-graphical-linux-desktop-applications-from-windows-10s-bash-shell/)
-   [FireFox for Linux](https://support.mozilla.org/en-US/kb/install-firefox-linux?cache=no)

**Comment by wwalser** [comment]
This is happening because of a change to the exit code of ```npm outdated```. In addition to changing ([see here](https://github.com/npm/npm/issues/5999)), a feature of the breaking change which was suppose to allow for the old behavior was [unintentionally left unimplemented](https://github.com/npm/npm/issues/16083).

This bug is a knock on effect from a bug in NPM which in turn causes a bug in [fbjs-scripts/gulp/check-dependencies](https://github.com/facebook/fbjs/blob/master/packages/fbjs-scripts/gulp/check-dependencies.js). Solutions are either to fix the bug in [NPM](https://github.com/npm/npm/issues/16083) or [this one in check dependencies](https://github.com/facebook/fbjs/blob/master/packages/fbjs-scripts/gulp/check-dependencies.js).

**Comment by alexeychikk** [comment]
I downgrade npm every time I need to build a new version of draft-js. Nice job, FB.

**Comment by Marckon** [comment]
it's 2020 now and I'm reading comments from 3 years ago. 😕
